// Shared student data — imported by both Student.jsx and StudentDetails.jsx

export const ALL_STUDENTS = [
  {
    id: "STU001",
    name: "Abhay Thakur",
    role: "Child",
    institution: "Tech Academy Accra",
    country: "India",
    age: "8-12",
    subscription: "Premium",
    active: true,
    avatar: "https://i.pravatar.cc/80?img=1",
    email: "Abhay@gmail.com",
    mobile: "+91 6416845451",
    parentEmail: "Parent@gmail.com",
    parentMobile: "+91 6416845451",
    enrollmentDate: "1/10/2023",
  },
  {
    id: "STU002",
    name: "Priya Sharma",
    role: "Junior Student",
    institution: "Tech Academy Accra",
    country: "India",
    age: "13-15",
    subscription: "Standard",
    active: true,
    avatar: "https://i.pravatar.cc/80?img=5",
    email: "priya@gmail.com",
    mobile: "+91 9876543210",
    parentEmail: "priyaParent@gmail.com",
    parentMobile: "+91 9876543210",
    enrollmentDate: "3/15/2023",
  },
  {
    id: "STU003",
    name: "Rohan Mehta",
    role: "Senior Student",
    institution: "Self Enroll",
    country: "India",
    age: "16-19",
    subscription: "Premium",
    active: true,
    avatar: "https://i.pravatar.cc/80?img=3",
    email: "rohan@gmail.com",
    mobile: "+91 8765432109",
    parentEmail: "rohanParent@gmail.com",
    parentMobile: "+91 8765432109",
    enrollmentDate: "6/20/2023",
  },
  {
    id: "STU004",
    name: "Sneha Gupta",
    role: "Adult",
    institution: "Tech Academy Accra",
    country: "India",
    age: "20+",
    subscription: "Standard",
    active: true,
    avatar: "https://i.pravatar.cc/80?img=9",
    email: "sneha@gmail.com",
    mobile: "+91 7654321098",
    parentEmail: "—",
    parentMobile: "—",
    enrollmentDate: "2/5/2023",
  },
  {
    id: "STU005",
    name: "Vikram Singh",
    role: "Adult",
    institution: "Tech Academy Accra",
    country: "India",
    age: "20+",
    subscription: "Standard",
    active: false,
    avatar: "https://i.pravatar.cc/80?img=7",
    email: "vikram@gmail.com",
    mobile: "+91 6543210987",
    parentEmail: "—",
    parentMobile: "—",
    enrollmentDate: "4/12/2023",
  },
  {
    id: "STU006",
    name: "Ananya Rao",
    role: "Adult",
    institution: "Tech Academy Accra",
    country: "India",
    age: "20+",
    subscription: "Standard",
    active: true,
    avatar: "https://i.pravatar.cc/80?img=6",
    email: "ananya@gmail.com",
    mobile: "+91 5432109876",
    parentEmail: "—",
    parentMobile: "—",
    enrollmentDate: "7/8/2023",
  },
];
